from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class PlanStep:
    """A single step in an execution plan."""
    tool_name: str
    arguments: Dict[str, Any] = field(default_factory=dict)
    rationale: str = ""


@dataclass
class Plan:
    """An execution plan generated by a planner."""
    query: str
    steps: List[PlanStep] = field(default_factory=list)
    notes: str = ""
